version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: memefeed
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: memefeed-postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memefeed -d memefeed-postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/resources/pg-data-models.sql:/docker-entrypoint-initdb.d/dbinit.sql
    networks:
      - memefeed-network

  celestia:
    container_name: celestia
    image: ghcr.io/celestiaorg/celestia-node:v0.13.5
    restart: on-failure
    environment:
      - NODE_TYPE=light
      - P2P_NETWORK=mocha
    ports:
      - "26657:26657"
      - "26658:26658"
      - "26659:26659"
      - "9090:9090"
    command: ["celestia", "light", "start", "--core.ip", "rpc-mocha.pops.one", "--p2p.network", "mocha", "--rpc.skip-auth"]
    healthcheck:
      test: ["CMD-SHELL", "curl -s -X POST http://localhost:26657 -H 'Content-Type: application/json' -d '{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"node.Ready\",\"params\":[]}' | grep '\"result\":\\[true\\]' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - memefeed-network

  memefeed:
    container_name: memefeed
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      # celestia:
        # condition: service_healthy
    environment:
      NODE_ENV: development
      PGUSER: memefeed
      PGHOST: postgres
      PGPASSWORD: mysecretpassword
      PGDATABASE: memefeed-postgres
      PGPORT: 5432
    links:
      - postgres
      # - celestia
    ports:
      - '3100:3100'
    networks:
      - memefeed-network
    volumes:
      - ~/.aws:/root/.aws

networks:
  memefeed-network:
    driver: bridge

volumes:
  postgres:
