version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest # TODO: pin to specific version?
    restart: always
    environment:
      POSTGRES_USER: memefeed
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: memefeed-postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memefeed -d memefeed-postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/resources/pg-data-models.sql:/docker-entrypoint-initdb.d/dbinit.sql
    networks:
      - memefeed-network

  memefeed:
    container_name: memefeed
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PGUSER: memefeed
      PGHOST: postgres
      PGPASSWORD: mysecretpassword
      PGDATABASE: memefeed-postgres
      PGPORT: 5432
    links:
      - postgres
    ports:
      - '3100:3100'
    networks:
      - memefeed-network

networks:
  memefeed-network:
    driver: bridge

volumes:
  postgres: